In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
#One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [5]:
df = df.sample(10000)

In [6]:
df.shape

(10000, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 48488 to 29063
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [15]:
df['sentiment'] = df['sentiment'].replace({'positive': 1, 'negative': 0})

/tmp/ipykernel_58/848478183.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'] = df['sentiment'].replace({'positive': 1, 'negative': 0})

In [16]:
df.head()

                                                  review  sentiment
48488  Well, I can safely say I'm human, Wong. And I ...          1
38634  'Maladolescenza' has the air of a dark fairy t...          0
44856  I got to see this just this last Friday at the...          1
40559  From the nepotism capitol of the world comes a...          0
3065   The movie " Inhabited" is about a family of fo...          1

In [45]:
#removing html tags

import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

''

In [46]:
# function to clean html tags

def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [47]:
df['review'] = df['review'].apply(clean_html)

In [48]:
#converting everything to lower

def convert_lower(text):
    return text.lower()

In [49]:
df['review'] = df['review'].apply(convert_lower)

In [50]:
#function to remove special characters

def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [51]:
df['review'] = df['review'].apply(remove_special)

In [52]:
# Remove the stop words
import nltk

In [53]:
from nltk.corpus import stopwords

In [54]:
df

               review  sentiment
48488            well          1
38634  maladolescenza          0
44856                          1
40559                          0
3065                           1
...               ...        ...
71           honestly          0
2656        potential          0
23214                          1
26538                          1
29063                          1

[10000 rows x 2 columns]

In [40]:
df

                 review  sentiment
48488            [well]          1
38634  [maladolescenza]          0
44856                []          1
40559                []          0
3065                 []          1
...                 ...        ...
71           [honestly]          0
2656        [potential]          0
23214                []          1
26538                []          1
29063                []          1

[10000 rows x 2 columns]

In [38]:
def remove_stopwords(text):
    x = []
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y = x[:]
    x.clear()
    return y

In [ ]:
df['review'] = df['review'].apply(remove_stopwords)

In [ ]:
#Perform stemming

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
y = []
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z = y[:]
    y.clear()
    return z

In [ ]:
df['review']= df['review'].apply(stem_words)

In [ ]:
# join back

def join_back(list_input):
    return " ".join(list_input)

In [ ]:
df['review']= df['review'].apply(join_back)

In [ ]:
X = df.iloc[:, 0:1].values

In [ ]:
X.shape

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=500)

In [ ]:
X=cv.fit_transform(df['review']).toarray()

In [ ]:
X.shape

In [ ]:
y = df.iloc[:, -1].values